[package]
name = "tg-perpus"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = "0.7.7"
lazy_static = "1.5.0"
rusqlite = "0.32.1"
serde = "1.0.210"
serde_derive = "1.0.210"
serde_json = "1.0.128"
tokio = {version = "1.40.0", features = ["full"]}
